config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'tasks#index'
  resources :tasks
  resources :notifications,only: [:index]
  namespace :admin do
    resources :users
  end
end

app/views/layouts/_header.html.slim
.header.pb-3
  nav#nav.navbar.navbar-expand-md.navbar-light.bg-light
    .container.navbar-nav
      .navber-brand
        = link_to "タスク管理",root_path, class: 'nav-link h4'
      .nav
        - if current_user
          / .dropdown
          /   a.dropdown-toggle.nav-link#drop herf="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          /     | 通知
          /   .dropdown-menu.p-3.text-muted
          /     = render partial: 'notifications/index', locals: {notifications: current_user.notifications}
          = link_to "タスク作成",new_task_path, class: 'nav-link'
          = link_to "ユーザー一覧",admin_users_path, class: 'nav-link'
          = link_to "#{current_user.name}",admin_user_path(current_user), class: 'nav-link',id:'user-link'
          = link_to "ログアウト",logout_path, method: :delete, class: 'nav-link'
          - if unchecked_notifications.any?
            p.text-danger ★
          = link_to "通知",notifications_path, class: 'nav-link'
        - else
          = link_to "ユーザー登録",new_admin_user_path, class: 'nav-link'
          = link_to "ログイン",login_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ElTraining
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      .notice
      - if flash.notice.present?
        .alert.alert-success
          = flash.notice
      .error
      - if flash.alert.present?
        .alert.alert-danger
          = flash.alert
      = yield